name: fluttercon25_client
publish_to: 'none'
description: Minimal Flutter client for Fluttercon25 demo
version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  connectrpc: ^1.0.0
  protobuf: ^4.2.0
  fixnum: ^1.1.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
